import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
const MapControlPanel = ({ mapType, setMapType, markerIconRules, markerNamePrefix, markerIconUrl, setMarkerNamePrefix, setMarkerIconUrl, handleUploadKmlKmz, handleUploadMarkerIcon, handleAddMarkerIconRule, handleRemoveMarkerIconRule, setIsDxfPreviewOpen, featureCount, buildingCount, roadCount, canExportDxf, isLoading, isLoadingBuildings, isLoadingRoads, }) => {
    return (_jsxs("div", { className: "absolute z-[1000] top-4 right-4 bg-white p-4 rounded-xl shadow-lg space-y-3 w-[320px] max-h-[90vh] overflow-y-auto", children: [_jsxs("div", { className: "space-y-1", children: [_jsx("label", { className: "text-xs font-semibold text-gray-700", children: "Upload KML / KMZ" }), _jsx("input", { type: "file", accept: ".kml,.kmz", onChange: handleUploadKmlKmz, className: "text-xs" })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { type: "button", onClick: () => setMapType('satellite'), className: `px-3 py-2 rounded-lg text-sm font-medium ${mapType === 'satellite'
                            ? 'bg-blue-600 text-white'
                            : 'bg-gray-100 text-gray-700'}`, children: "Satellite" }), _jsx("button", { type: "button", onClick: () => setMapType('vector'), className: `px-3 py-2 rounded-lg text-sm font-medium ${mapType === 'vector'
                            ? 'bg-blue-600 text-white'
                            : 'bg-gray-100 text-gray-700'}`, children: "Vector" })] }), _jsxs("div", { className: "border-t pt-3 space-y-2", children: [_jsx("div", { className: "text-sm font-semibold text-gray-800", children: "Ubah Icon Marker" }), _jsx("input", { type: "text", value: markerNamePrefix, onChange: (e) => setMarkerNamePrefix(e.target.value), placeholder: "Awalan label, contoh: MMG", className: "w-full border rounded-lg px-3 py-2 text-sm" }), _jsx("input", { type: "text", value: markerIconUrl, onChange: (e) => setMarkerIconUrl(e.target.value), placeholder: "URL icon marker", className: "w-full border rounded-lg px-3 py-2 text-sm" }), _jsx("input", { type: "file", accept: "image/*", onChange: handleUploadMarkerIcon, className: "text-xs" }), markerIconUrl && (_jsxs("div", { className: "flex items-center gap-2 text-xs text-gray-600", children: [_jsx("span", { children: "Preview:" }), _jsx("img", { src: markerIconUrl, alt: "Preview icon", className: "w-8 h-8 object-contain" })] })), _jsx("button", { type: "button", onClick: handleAddMarkerIconRule, className: "w-full bg-green-600 text-white rounded-lg px-3 py-2 text-sm font-medium", children: "Terapkan Icon" }), markerIconRules.length > 0 && (_jsxs("div", { className: "space-y-2 pt-2", children: [_jsx("div", { className: "text-xs font-semibold text-gray-700", children: "Daftar aturan icon:" }), markerIconRules.map((rule) => (_jsxs("div", { className: "flex items-center justify-between gap-2 bg-gray-50 border rounded-lg px-2 py-2", children: [_jsxs("div", { className: "flex items-center gap-2 min-w-0", children: [_jsx("img", { src: rule.iconUrl, alt: rule.namePrefix, className: "w-7 h-7 object-contain shrink-0" }), _jsxs("div", { className: "text-xs truncate", children: ["Label: ", rule.namePrefix, "*"] })] }), _jsx("button", { type: "button", onClick: () => handleRemoveMarkerIconRule(rule.namePrefix), className: "text-xs text-red-600", children: "Hapus" })] }, rule.namePrefix)))] }))] }), _jsxs("div", { className: "border-t pt-3 space-y-2", children: [_jsx("div", { className: "text-sm font-semibold text-gray-800", children: "Export DXF AutoCAD" }), _jsx("button", { type: "button", disabled: !canExportDxf, onClick: () => setIsDxfPreviewOpen(true), className: `w-full rounded-lg px-3 py-2 text-sm font-medium ${canExportDxf
                            ? 'bg-black text-white'
                            : 'bg-gray-200 text-gray-400 cursor-not-allowed'}`, children: "Preview Tampilan DXF" }), _jsx("div", { className: "text-[11px] text-gray-500 leading-relaxed", children: "Preview akan menampilkan simulasi tampilan seperti AutoCAD." })] }), featureCount > 0 && (_jsxs("div", { className: "text-xs text-gray-600 space-y-1 border-t pt-3", children: [_jsxs("div", { children: ["Total data KML/KMZ: ", featureCount] }), _jsxs("div", { children: ["Bangunan dalam polygon: ", buildingCount] }), _jsxs("div", { children: ["Jalan dalam polygon: ", roadCount] })] })), isLoading && (_jsx("div", { className: "text-xs text-blue-600", children: "Memuat data peta..." })), isLoadingBuildings && (_jsx("div", { className: "text-xs text-green-600", children: "Mengambil data bangunan..." })), isLoadingRoads && (_jsx("div", { className: "text-xs text-orange-600", children: "Mengambil data jalan..." }))] }));
};
export default MapControlPanel;
