import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Download, ImageIcon, Layers, Map, Ruler, Upload, } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger, } from '@/components/ui/tooltip';
const MapFloatingMenu = ({ mapType, setMapType, canExportDxf, onOpenMarkerSheet, onOpenRoadWidthSheet, onExportDxf, onUpload, }) => {
    return (_jsx(TooltipProvider, { children: _jsxs(Card, { className: "absolute left-4 top-4 z-[1000] flex items-center gap-2 p-2 shadow-xl", children: [_jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(Button, { size: "icon", variant: mapType === 'satellite' ? 'default' : 'outline', onClick: () => setMapType('satellite'), children: _jsx(Layers, { className: "h-4 w-4" }) }) }), _jsx(TooltipContent, { children: "Satellite" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(Button, { size: "icon", variant: mapType === 'vector' ? 'default' : 'outline', onClick: () => setMapType('vector'), children: _jsx(Map, { className: "h-4 w-4" }) }) }), _jsx(TooltipContent, { children: "Vector" })] }), _jsx("div", { className: "h-6 w-px bg-border" }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(Button, { size: "icon", variant: "outline", onClick: onOpenMarkerSheet, children: _jsx(ImageIcon, { className: "h-4 w-4" }) }) }), _jsx(TooltipContent, { children: "Ubah Icon Marker" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(Button, { size: "icon", variant: "outline", onClick: onOpenRoadWidthSheet, children: _jsx(Ruler, { className: "h-4 w-4" }) }) }), _jsx(TooltipContent, { children: "Atur Lebar Jalan" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsx(Button, { size: "icon", disabled: !canExportDxf, onClick: onExportDxf, children: _jsx(Download, { className: "h-4 w-4" }) }) }), _jsx(TooltipContent, { children: "Export DXF" })] }), _jsxs(Tooltip, { children: [_jsx(TooltipTrigger, { asChild: true, children: _jsxs("label", { children: [_jsx("input", { type: "file", accept: ".kml,.kmz", className: "hidden", onChange: onUpload }), _jsx(Button, { size: "icon", variant: "outline", asChild: true, children: _jsx("span", { children: _jsx(Upload, { className: "h-4 w-4" }) }) })] }) }), _jsx(TooltipContent, { children: "Upload ulang file" })] })] }) }));
};
export default MapFloatingMenu;
