import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Trash2 } from 'lucide-react';
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle, } from '@/components/ui/sheet';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { ScrollArea } from '@/components/ui/scroll-area';
const MarkerIconSheet = ({ open, onOpenChange, markerIconRules, markerNamePrefix, markerIconUrl, setMarkerNamePrefix, setMarkerIconUrl, handleUploadMarkerIcon, handleAddMarkerIconRule, handleRemoveMarkerIconRule, }) => {
    return (_jsx(Sheet, { open: open, onOpenChange: onOpenChange, children: _jsxs(SheetContent, { className: "w-[380px] sm:max-w-md", children: [_jsxs(SheetHeader, { children: [_jsx(SheetTitle, { children: "Ubah Icon Marker" }), _jsx(SheetDescription, { children: "Upload gambar icon. Saat export DXF, gambar otomatis diubah menjadi DXF BLOCK vector, bukan circle." })] }), _jsxs("div", { className: "mt-6 space-y-5", children: [_jsxs("div", { className: "space-y-2", children: [_jsx(Label, { children: "Awalan Label" }), _jsx(Input, { value: markerNamePrefix, onChange: (e) => setMarkerNamePrefix(e.target.value), placeholder: "Contoh: MMG" })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Label, { children: "URL Icon" }), _jsx(Input, { value: markerIconUrl, onChange: (e) => setMarkerIconUrl(e.target.value), placeholder: "https://..." })] }), _jsxs("div", { className: "space-y-2", children: [_jsx(Label, { children: "Upload Icon" }), _jsx(Input, { type: "file", accept: "image/*", onChange: handleUploadMarkerIcon })] }), markerIconUrl && (_jsxs("div", { className: "flex items-center gap-3 rounded-lg border p-3", children: [_jsx("img", { src: markerIconUrl, alt: "Preview icon", className: "h-10 w-10 object-contain" }), _jsx("div", { className: "text-sm text-muted-foreground", children: "Preview icon marker" })] })), _jsx(Button, { className: "w-full", onClick: handleAddMarkerIconRule, disabled: !markerNamePrefix.trim() || !markerIconUrl.trim(), children: "Terapkan Icon" }), _jsxs("div", { className: "space-y-3", children: [_jsx("div", { className: "text-sm font-medium", children: "Daftar Aturan" }), _jsx(ScrollArea, { className: "h-[300px] pr-3", children: _jsxs("div", { className: "space-y-2", children: [markerIconRules.length === 0 && (_jsx("div", { className: "rounded-lg border border-dashed p-4 text-sm text-muted-foreground", children: "Belum ada aturan icon." })), markerIconRules.map((rule) => (_jsxs("div", { className: "flex items-center justify-between rounded-lg border p-3", children: [_jsxs("div", { className: "flex min-w-0 items-center gap-3", children: [_jsx("img", { src: rule.iconUrl, alt: rule.namePrefix, className: "h-9 w-9 shrink-0 object-contain" }), _jsxs("div", { className: "min-w-0", children: [_jsxs(Badge, { variant: "secondary", children: [rule.namePrefix, "*"] }), _jsxs("div", { className: "mt-1 truncate text-xs text-muted-foreground", children: ["Block: ", rule.dxfBlockName] }), _jsxs("div", { className: "truncate text-xs text-muted-foreground", children: ["Vector cells: ", rule.dxfCells.length] })] })] }), _jsx(Button, { size: "icon", variant: "ghost", onClick: () => handleRemoveMarkerIconRule(rule.namePrefix), children: _jsx(Trash2, { className: "h-4 w-4 text-destructive" }) })] }, rule.namePrefix)))] }) })] })] })] }) }));
};
export default MarkerIconSheet;
